name: Changelog generator
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push tag
      id: '0.7.0'
      uses: mathieudutour/github-tag-action@v5.6
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')

    # - name: Changelog generator
    #   uses: dittrichlucas/changelog-generator@main
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     repo: ${{ github.repository }}

    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     commit-message: Update report
    #     committer: GitHub <noreply@github.com>
    #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #     signoff: true
    #     branch: example-patches
    #     delete-branch: true
    #     title: '[Example] Update report'
    #     body: |
    #       Update report
    #       - Updated with *today's* date
    #       - Auto-generated by [create-pull-request][1]

    #       [1]: https://github.com/peter-evans/create-pull-request
    #     assignees: lucasdittrichzup
    #     draft: false

    # - name: Check outputs
    #   run: |
    #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
