name: Changelog generator
on:
  workflow_dispatch:
    inputs:
      new_tag:
        description: 'Tag da nova release'
        required: true

jobs:
  test:
    runs-on: ubuntu-latest
    env:

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Push tag
      uses: anothrNick/github-tag-action@1.26.0
      env:
        CUSTOM_TAG: ${{ github.event.inputs.new_tag }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: false

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.event.inputs.new_tag }}

    # - name: Changelog generator
    #   uses: dittrichlucas/changelog-generator@main
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     repo: ${{ github.repository }}

    # - name: Create Pull Request
    #   id: cpr
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.GITHUB_TOKEN }}
    #     commit-message: Update report
    #     committer: GitHub <noreply@github.com>
    #     author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
    #     signoff: true
    #     branch: example-patches
    #     delete-branch: true
    #     title: '[Example] Update report'
    #     body: |
    #       Update report
    #       - Updated with *today's* date
    #       - Auto-generated by [create-pull-request][1]

    #       [1]: https://github.com/peter-evans/create-pull-request
    #     assignees: lucasdittrichzup
    #     draft: false

    # - name: Check outputs
    #   run: |
    #     echo "Pull Request Number - ${{ steps.cpr.outputs.pull-request-number }}"
    #     echo "Pull Request URL - ${{ steps.cpr.outputs.pull-request-url }}"
