name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Informe uma tag (e.g.: 0.0.0)'
        required: true
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Gerar o changelog
        run: |
          echo "Install dependencies"
          gem install github_changelog_generator

          echo "Get the release tag"
          LT=$(git tag | tail -1); echo $LT

          echo "Generate changelog"
          github_changelog_generator \
          -u lucasdittrichzup \
          -p changelog-action-test
          -since-tag $LT
          # --token ${{ secrets.GITHUB_TOKEN }}
          # --enhancement-labels feature,Feature \
          # --exclude-labels duplicate,question,invalid,wontfix

          # echo "Tag: ${{ github.event.inputs.tag }}"

          echo "Check the generated file"
          cat CHANGELOG.md

      # - name: Gerar release/tag

      # - name: Abrir a PR com o changelog

      # - name: Atualizar release latest com a descrição das alterações
