name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Informe uma tag (e.g.: 0.0.0)'
        required: true
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gerar o changelog
        run: |
          echo "Install dependencies"

